### ISSUE TITLE
Not working when used inside an $mdDialog

### ISSUE THREAD

**Issue by vineethvnair0** [ahlechandre/mdl-stepper#10]
HI,

I am trying to use the stepper inside an mdDialog. The stepper is getting displayed successfully, but when I click on the continue button, its keep on loading its not opening the next step. Please find the plunker link below.

https://plnkr.co/edit/ixMI8FKbhyTgL5sYieVa?p=preview

Click on the test button to open the mdDialog

**Comment by axdemelas** [comment]
It's working.

The instance of `MaterialStepper` is only available after upgraded.

e.g.

``` js
var element = document.querySelector('.mdl-stepper');
var stepper; // element.MaterialStepper == undefined
componentHandler.upgradeAllRegistered();
stepper = element.MaterialStepper;
```
