### ISSUE TITLE
Dynamic height for vertical stepper

### ISSUE THREAD

**Issue by barrysteyn** [ahlechandre/mdl-stepper#12]
Vertical steppers are constrained to 320px. It would be very useful if they were instead allowed a dynamic height.

**Comment by barrysteyn** [comment]
Here is one way to do this:

After line 348 of stepper.js, insert: `document.styleSheets[0].addRule('.mdl-step.is-active:not(:last-child) .mdl-step__label-indicator:after', 'height: '+(step.content.clientHeight+122)+'px');`

Then remove the css rule `.mdl-step.is-active:not(:last-child) .mdl-step__label-indicator:after` (it starts on line 175 of stepper.css)

**Comment by axdemelas** [comment]
@barrysteyn Thanks for suggestion, it is certainly a good solution. But I would keep the style rules (as possible) in the stylesheets and I will work on that as a CSS-only feature.

**Comment by axdemelas** [comment]
Hi @barrysteyn,

After `v1.1.4` (5ff38bbe0dee2676af7c9aada8819f793fd7c427), also available on NPM, you can have dynamic height for vertical steppers. To do this you only need to change the `height` property of steps (default `460px`):

``` css
.mdl-step {
   height: 820px;
}
```

Complete guide to handle the dimensions of steppers and steps soon in [component page](http://ahlechandre.github.io/mdl-stepper/component/).
