### ISSUE TITLE
Step label indicator error: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by bresson** [ahlechandre/mdl-stepper#18]
model.labelIndicator = model.label.querySelector('.' + this.CssClasses_.STEP_LABEL_INDICATOR);
inside stepper.js

This is the error: 
stepper.js:281 : Uncaught TypeError: Cannot read property 'querySelector' of null

**Comment by axdemelas** [comment]
Following [docs](http://ahlechandre.github.io/mdl-stepper/component/):

> All step has a label. Label includes a title with text and optionally the supporting message (e.g. Optional).

``` html
<li class="mdl-step">
  <span class="mdl-step__label">
    <span class="mdl-step__title">
      <span class="mdl-step__title-text">Name of step 1</span>
      <span class="mdl-step__title-message">Summarize if needed</span>
    </span>
  </span>
  <!-- content -->
  <!-- actions -->
</li>
```

You coded the label element into step? If yes then post a codepen or jsfiddle with your full markup here.

**Comment by bresson** [comment]
OK Thanks - I confirmed the DOM element was on the page yet the error still appeared. However, I took the code from your samples and inserted them into my page and everything works.
