### ISSUE TITLE
Using mdl-stepper together with zodiase:mdl in meteor

### ISSUE THREAD

**Issue by pineapplegum** [ahlechandre/mdl-stepper#2]
Great work on this component! It looks really good. 

I would like to use the stepper in a meteor application which already uses the zodiase:mdl package (see https://github.com/Zodiase/meteor-mdl). So, what I've tried is to add the stepper js to my meteor application, hoping that it will be able to use the componentHandler from zodiase:mdl.  

However, when trying to do so, I get an error in the browser saying that componentHandler is not defined (the error comes from line 881 in stepper.js where it tries to register the component). 

My guess is that the application is trying to load the stepper.js files before the componentHandler from zodiase:mdl is defined. Do you happen to know if there's any workaround that can make this work? 

Thanks

**Comment by axdemelas** [comment]
I don't know how zodiase works at core but we could consider some reasons for this: 
1. `componentHandler` is not available globally 
2. `componentHandler` is not loaded yet. 

Ok, reading the zodiase [ChangeLog.md](https://github.com/Zodiase/meteor-mdl/blob/b3a4e70a65c85df1455cf025b442fed1a0ae4169/ChangeLog.md#change-log) at v1.0.0-4 it says:

> - v1.0.0-4
>   - (...)
>   - Added a namespace `MDl` while maintaining `componentHandler` available globally. You can also use `Mdl.componentHandler` if it looks better.
>   - (...)

They recommend that you use `MDL.componentHandler` but `componentHandler` still's globally. So this problem would be related to the second reason.   

Considering that you [started](https://ahlechandre.github.io/mdl-stepper/started/) correctly: adding the `stepper.js` (or minified) file after mdl files, you could post a code example that would help us (gist, codepen)

**Comment by pineapplegum** [comment]
Ok, I managed to resolve the problem by placing the js in the public folder in mye Meteor app structure, and then loading the js on startup of the application. I close the issue now as I think this is more related to Meteor's loading of external scripts than to the mdl-stepper itself!
