### ISSUE TITLE
(typeof stepperElement.MaterialStepper) undefined

### ISSUE THREAD

**Issue by sarveshacharya** [ahlechandre/mdl-stepper#21]
@ahlechandre 

I am integrating mdl-stepper with meteor and dynamically adding the stepper. 
`var stepperElement = document.querySelector('.mdl-stepper');
console.log(typeof stepperElement.MaterialStepper); // undefined
componentHandler.upgradeAllRegistered();
console.log(typeof stepperElement.MaterialStepper); // object` 
In the last step i am getting undefined instead of object

All libraries are loaded, working fine in html but the issue is there in meteor.

**Comment by axdemelas** [comment]
Hi @acharyasarvesh,

Seems like a problem with `componentHandler` scope.

I don't know how Meteor works but it might change things. Are you using some package like [Zodiase MDL](https://github.com/Zodiase/meteor-mdl) to integrate Material Design Lite with Meteor? 

If not I would recommend. If yes then we already have discussed about that before on #2.

**Comment by sarveshacharya** [comment]
Hi @ahlechandre 

Yes i am using [Zodiase MDL](https://github.com/Zodiase/meteor-mdl) to integrate Material Design Lite

Is it that i should load MDL explicitly?

And are you planning to release meteor version in future?

**Comment by axdemelas** [comment]
You've tried to solve the issue? There are some code problem? If you're using, what is the point?

This may be more related to Meteor's loading of external scripts than to the mdl-stepper.

Basically:
1. Make sure that you are integrating correctly MDL + Meteor (google it if you aren't certain).
2. Make sure that Material Design Lite script is loaded before mdl-stepper script ([see more](https://github.com/ahlechandre/mdl-stepper#javascript)). 
3. Make sure that `componentHandler` is available globally. Stepper uses this global to upgrade itself.
4. Try another time the initial attempt (described in your issue).
5. See things working.

``` js
(typeof window.componentHandler !== 'undefined') // Should be "true"
```

No, I'm not looking for a Meteor version for now.
