### ISSUE TITLE
Missing source map

### ISSUE THREAD

**Issue by sucre666** [ahlechandre/mdl-stepper#22]
Hi,

When I open Chrome console I get this:
Failed to parse SourceMap **/lib/mdl-stepper/stepper.css.min.map

At the end of stepper.css.min file there is: /*# sourceMappingURL=stepper.css.min.map */
I think it should be removed if source map is not included with build. 

Regards,

**Comment by axdemelas** [comment]
My bad, the source maps are now included with build.
