### ISSUE TITLE
Ability to align actions

### ISSUE THREAD

**Issue by ghost** [ahlechandre/mdl-stepper#24]
Could there be a way to align the action buttons ourselves? My use case is to put a "Next" button in the center.

**Comment by odyright** [comment]
Do you men in Angular Material? Yes you can do it yourself … it use Flexbox . So you can align button where you want.

**Comment by axdemelas** [comment]
Looking the [Steppers spec page](https://material.google.com/components/steppers.html), I can't find spec about the ability to align buttons (e.g. centering). I could consider that it is outside the scope of component.

### Align actions polyfill

As @odyright said, the actions container/outer (`.mdl-step__actions`) is a flexbox then you can use `justify-content` property to do that.

See centering example:

``` css
.mdl-step.is-active .mdl-step__actions {
    justify-content: center;
}
```

**Comment by ghost** [comment]
@ahlechandre I see, I was trying to do flexbox with my own custom `<div>`
