### ISSUE TITLE
MDL-Stepper not working with IE10 and Safari 8

### ISSUE THREAD

**Issue by ghost** [ahlechandre/mdl-stepper#27]
Hi,

I have use mdl-stepper on website : https://sim-usa.mobi/activation/.
It works fine with chrome, firefox, Edge..

But with IE 10 and Safari 8, Stepper not appears.

Can you help me ?

**Comment by axdemelas** [comment]
Please, provide more details about what is not working

**Comment by ghost** [comment]
With chrome, the stepper is ok : 
![chrome](https://cloud.githubusercontent.com/assets/17589206/18376462/5974cebc-7657-11e6-9a1a-31a83324635f.png)

With IE10 or Safari 8 it doesn't appear :
![ie10](https://cloud.githubusercontent.com/assets/17589206/18376468/63ef222a-7657-11e6-9554-361cfae7de9a.png)

There is no JS errors

**Comment by axdemelas** [comment]
Stepper uses [Flexbox](http://caniuse.com/#feat=flexbox) for most of its elements and these versions do not seem to support this.

![sem titulo](https://cloud.githubusercontent.com/assets/7119058/18398825/cf4beae2-76a4-11e6-9573-020784bb0dff.png)
