### ISSUE TITLE
Publish as a NPM package

### ISSUE THREAD

**Issue by macx** [ahlechandre/mdl-stepper#3]
I would love to use it as a NPM package by providing a `package.json`.

[NPM (as a developer)](https://gist.github.com/coolaj86/1318304)

**Comment by axdemelas** [comment]
Ok, thanks for suggestion. I'll publish it soon.

**Comment by axdemelas** [comment]
@macx look at pull request #7

**Comment by macx** [comment]
Cool. To provide an extra layer of information, a release would be nice, too.

**Comment by axdemelas** [comment]
@macx Yeah, but for now my time is pretty busy. I will return to work on this project soon.

**Comment by axdemelas** [comment]
@macx 

``` bash
npm install --save mdl-stepper
```
