### ISSUE TITLE
is correct add a button in label?

### ISSUE THREAD

**Issue by lcmartinezdev** [ahlechandre/mdl-stepper#46]
Hi,

I want to add "añadir" button but I don't know if is correct and possible. 

![image](https://user-images.githubusercontent.com/4006316/30866534-262373c2-a29f-11e7-8e45-b37133c1862a.png)

if somebody can help me, thank you.

**Comment by axdemelas** [comment]
Please, check the component guideline.

https://material.io/guidelines/components/steppers.html
