### ISSUE TITLE
Horizontal type support

### ISSUE THREAD

**Issue by axdemelas** [ahlechandre/mdl-stepper#8]
> Horizontal steppers are ideal when the contents of one step depend on an earlier step.

[Type of steppers spec](https://www.google.com/design/spec/components/steppers.html#steppers-types-of-steppers)

![cats](https://cloud.githubusercontent.com/assets/7119058/13622737/8ab4944e-e57f-11e5-86e9-532efba7c49e.jpg)

**Comment by barrysteyn** [comment]
@ahlechandre Can you sketch out what we  need to make this horizontal. I have not looked at the source, but my general thinking is a media query to determine if we are on a mobile device, and if so, render it horizontal (easier said than done)

**Comment by axdemelas** [comment]
@barrysteyn Hi, we could provide the horizontal and vertical types for large screens and vertical for small screens. I'm not certain but we may need to refactor the CSS to support horizontal type. 

I did not have time to think in many details when I wrote the component. Feel free to propose solutions. :)

| Class | Effect | Remarks |
| --- | --- | --- |
| `mdl-stepper` | Defines a stepper container as vertical type. | Required |
| `mdl-stepper--horizontal` | Defines a stepper container as horizontal type on tablets or large. | Manually added |

**Comment by barrysteyn** [comment]
I finally found some time to look into this, however, it is not a simple "just make the list elements float left" type of problem... It seems to be more complex. I know CSS, but I don't use it often. Could you sketch out more ideas for how this can be done.

**Comment by barrysteyn** [comment]
@ahlechandre Look at this: https://codepen.io/sharafat_8271/pen/KVWMXP

**Comment by axdemelas** [comment]
Look this voodoo that I did in 10 minutes at dev tools. 

![sem titulo](https://cloud.githubusercontent.com/assets/7119058/15959609/f104d93e-2ed1-11e6-8bf6-493b322f8b70.png)

> No additional markup. Using only `mdl-stepper--horizontal` modifier.

**Comment by lgabeskiria** [comment]
@ahlechandre can you share "horizontal" stepper code?

**Comment by barrysteyn** [comment]
@ahlechandre When I add the mdl-stepper--horizontal class like you have done, I get very different results unfortunately. Would be super grateful if you could share the code.

**Comment by axdemelas** [comment]
Me and @barrysteyn talking a little about **horizontal type support**.

I really would like to keep the markup without changes.

When designed, I didn't think about it but I want to believe that BEM approach can help us to implement this feature. As said previously, would be nice if we can provide just a modifier css class (e.g. `mdl-stepper--horizontal`) and all changes ocurring in stylesheet, without adding more markup ramifications.

This is the major preference but, obviously, not mandatory. 

I even wanting it, but now we need to do initial attempts because I'm not certain if it's (and how it's) possible.

**Comment by barrysteyn** [comment]
I agree - lets not change the markup. @ahlechandre if your "voodoo" above is working, then why not just use it? Not changing the markup is definitely the way to go.

**Comment by axdemelas** [comment]
@barrysteyn Sorry for any explanation. The screenshot code's running locally, it was just a test to check the viability of horizontal type support without adding or changing markup (e.g. creating a new structure different than current HTML List). 

There are also more style rules than just seen whitin the modifier `mdl-stepper--horizontal`.

**Comment by axdemelas** [comment]
@levan-g For now, I'm working on that and I will share it when get a solid support.

**Comment by barrysteyn** [comment]
Thanks so much @ahlechandre - this is very appreciated.

**Comment by barrysteyn** [comment]
Thanks @ahlechandre - I will test your horizontal stepper. This looks very cool.

**Comment by barrysteyn** [comment]
@ahlechandre - it works beautifully. Thank you so much.

**Comment by axdemelas** [comment]
Apparently, horizontal steppers support is stable on major browsers at this point.

Demonstration (for desktop users) here: https://ahlechandre.github.io/mdl-stepper/demo/

Create a new issue for any trouble/bug/feature request around this type of stepper.
