### ISSUE TITLE
Not working when used along with UI router

### ISSUE THREAD

**Issue by vineethvnair0** [ahlechandre/mdl-stepper#9]
I am trying to use mdl-stepper, when I add the stepper in the index.html page its working fine. Please find the plunker link below

https://plnkr.co/edit/m7EGqw?p=preview

But when I do the same thing inside a separate html and use ui-router, its not working.
https://plnkr.co/edit/ixMI8FKbhyTgL5sYieVa?p=preview

**Comment by axdemelas** [comment]
It's working. :)

Stepper uses (`componentHandler`) the pattern of Material Design Lite to registration new components and upgrade automatically on document load and components that may be added after initial page load.

In your case, Stepper was added by asynchronous request (after initial page load). To do so, you must upgrade manually the Stepper component to work as well.

I don't know how `angular.js` works. Code in your AJAX success callback:

``` js
// The Stepper registers itself. Since you are adding dynamically, 
// then you need to upgrade. This line will upgrade all components that must.
componentHandler.upgradeAllRegistered();
```

``` js
// or only Stepper component.
var element = document.querySelector('.mdl-stepper#stepper-non-linear');
componentHandler.upgradeElement(element, 'MaterialStepper');
```

Looking into your `script.js`, I do this workaround. Test:

``` js
var HomeController = function ($scope) {

        $scope.demoNonLinear = function () {
            var element = document.querySelector('.mdl-stepper#stepper-non-linear');
            if (!element) return false;
            var stepper = element.MaterialStepper;
            var steps = element.querySelectorAll('.mdl-step');
            var step;

            // Upgrade the component.
            if (typeof componentHandler === 'undefined') {
              console.log('Missing componentHandler');
            } else {
              console.log('componentHandler is available');
              componentHandler.upgradeAllRegistered();
            }

            for (var i = 0; i < steps.length; i++) {
                step = steps[i];
                step.addEventListener('onstepnext', function (e) {
                    setTimeout(function () {
                        stepper.next();
                    }, 4000);
                });
            }

        };
    };
```

**Comment by vineethvnair0** [comment]
Hi thanks for the correction. But now I am trying to add it inside an md-dialog and its not working. 
Please find the plunker url below
https://plnkr.co/edit/ixMI8FKbhyTgL5sYieVa?p=preview

**Comment by vineethvnair0** [comment]
thanks that's working

**Comment by vineethvnair0** [comment]
But when I click on the continue button the second one is not opening ?

**Comment by vineethvnair0** [comment]
its throwing an error in the console saying 

script.js:40 Uncaught TypeError: Cannot read property 'next' of undefined

**Comment by axdemelas** [comment]
@vineethvnair0  #10 solution here.
